#!/usr/bin/env python3

from collections import defaultdict

#Track failed log-in attempts by ip
attempts = defaultdict(int)

with open("auth.log", "r") as file:
    for line in file:
        if "Failed password" in line:
            parts = line.split()
            ip_index = parts.index("from") + 1
            ip = parts[ip_index]
            attempts[ip] += 1

#Flag brute force attempts
print("Brute force attempts detected:")
for ip, count in attempts.items():
    if count > 4:
        print(f"{ip} -> {count} failed attempts")
